- name: install packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apt-utils
    - autoconf
    - automake
    - bc
    - binutils
    - bison
    - build-essential
    - ca-certificates
    - cmake
    - dialog
    - dmidecode
    - doxygen
    - flex
    - g++
    - gcc-multilib
    - gdb
    - gettext
    - git
    - iasl
    - libcurl-dev
    - liblzma-dev
    - libssl-dev
    - libtool
    - locales
    - m4
    - make
    - makedev
    - ncurses-dev
    - nfs-common
    - ntpdate
    - pkg-config
    - python
    - python-dev
    - ssh
    - sudo
    - tmux
    - vim
    - wget
    - wpasupplicant
    - xen-linux-system-amd64
    - xen-system-amd64
    - xen-tools
    - zlib1g-dev

