- name: check if /lib/modules/{{ version }} exist
  stat:
    path: "/lib/modules/{{ version }}"
  register: mod_dir
- name: install Linux "{{ version }}"
  apt:
    deb: "{{ item }}"
  with_items:
    - linux-headers-{{ version }}_{{ version }}-1_amd64.deb
    - linux-image-{{ version }}_{{ version }}-1_amd64.deb
    - linux-image-{{ version }}-dbg_{{ version }}-1_amd64.deb
    - linux-libc-dev_{{ version }}-1_amd64.deb
  when: not mod_dir.stat.exists
