- name: copy preseed.cfg
  copy:
    src: files/preseed.cfg
    dest: /var/netboot/preseed.cfg

- name: copy preseed_ubuntu.cfg
  copy:
    src: files/preseed_ubuntu.cfg
    dest: /var/netboot/preseed_ubuntu.cfg

- name: deploy menu.ipxe
  template:
    src: templates/menu.ipxe.j2
    dest: /var/netboot/menu.ipxe

- name: create kernels directory
  file:
    path: /var/netboot/kernels
    state: directory

- name: create Xen dev symlink
  file:
    src: xen-4.8-amd64
    dest: /var/netboot/kernels/xen-dev
    state: link
    #TODO: remove force after adding xen kernel
    force: yes

- name: create Linux dev symlink
  file:
    src: vmlinuz-4.14.y
    dest: /var/netboot/kernels/vmlinuz-dev
    state: link
    #TODO: remove force after adding xen kernel
    force: yes

#Following kernels should be deployed to /var/netboot/kernels

#TODO: obtain Xen kernel from debian - artifact of rootfs building
#TODO: obtain Debian with 4.9.y - artifact of rootfs building
#TODO: obtain Debian with 4.14.y - artifact of rootfs building

#TODO: obtain Voyage Linux - have to be obtained from our cloud, since we do
#not support extraction from ISO
