- name: Copy Debian rootfs
  copy:
    src: "results/rootfs-{{ release_version }}.tar.gz"
    dest: /tmp/rootfs-{{ release_version }}.tar.gz

- name: Copy Linux 4.9.y
  copy:
    src: "results/vmlinuz-{{ linux_4_9 }}"
    dest: /var/netboot/kernels/vmlinuz-{{ linux_4_9 }}

- name: Copy Linux 4.14.y
  copy:
    src: "results/vmlinuz-{{ linux_4_14 }}"
    dest: /var/netboot/kernels/vmlinuz-{{ linux_4_14 }}

- name: Copy Linux Xen dev
  copy:
    src: "results/vmlinuz-xen-dev"
    dest: /var/netboot/kernels/vmlinuz-xen-dev

- name: Copy Xen 4.8
  copy:
    src: "results/xen-4.8-amd64"
    dest: /var/netboot/kernels/xen-4.8-amd64

- name: Copy Xen dev
  copy:
    src: "results/xen-dev"
    dest: /var/netboot/kernels/xen-dev

- name: Copy xen-image-minimal-genericx86-64.ext4
  copy:
    src: "results/xen-image-minimal-genericx86-64.ext4"
    dest: /var/xen-image-minimal-genericx86-64.ext4

- name: create Linux 4.14.y symlink
  file:
    src: vmlinuz-{{ linux_4_14 }}
    dest: /var/netboot/kernels/vmlinuz-4.14.y
    state: link
    force: yes

- name: create Linux 4.9.y symlink
  file:
    src: vmlinuz-{{ linux_4_9 }}
    dest: /var/netboot/kernels/vmlinuz-4.9.y
    state: link
    force: yes

- name: Unarchive Debian rootfs
  unarchive:
    src: /tmp/rootfs-{{ release_version }}.tar.gz
    dest: /var
    remote_src: yes
    keep_newer: yes
    group: debian
    owner: debian
